# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
R:
  - 4.0.0
sudo: false
cache: packages

r_packages:
  - covr

matrix:
  include:
  - r: devel
    after_success:
    - export PKGDOWN=no
  - r: release
    before_script: Rscript -e 'install.packages(c("earth", "tidyverse", "mlbench", "pkgdown"))'
    after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'pkgdown::build_site(run_dont_run = TRUE)' && export PKGDOWN=yes
  - r: release
    name: tidyr-devel
    before_script: Rscript -e "remotes::install_github('tidyverse/tidyr')"
    after_success:
    - export PKGDOWN=no
  - r: release
    name: dplyr-devel
    before_script: Rscript -e "remotes::install_github('tidyverse/dplyr')"
    after_success:
    - export PKGDOWN=no
  - r: release
    name: parcats-devel
    before_script:
      - git clone https://github.com/erblast/parcats.git
      - Rscript -e "remotes::install_github('erblast/parcats')"
    script:
      - Rscript -e "devtools::check('.')"
      - Rscript -e "devtools::check('parcats/')"
    after_success:
    - export PKGDOWN=no
    
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local-dir: docs
  on:
    branch: master
    condition: $PKGDOWN = yes
