# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
R:
  - 3.5.3
sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
